travis:
  secure:
    BINSTAR_TOKEN: dnBlnkkZsYf8SjiMX8C9PdjbUog1Ds3z98gGZS/dh+Ww1xk1xFbf5/AjPiMCSbYs/WUWJgS+8IKJ0HKhDnUQgHu7Nt0HpzRlTS8b8wowI5xoHHexZdY4uFQC+zT0+HMNIHBzBY5Vp3+RpMgd0ELYGC3wGuIQhZBDLnn23DuVXzIeyHlW+3GXruGc/MfcD/obPkf8N4csLj4VDEEwJyFmrbbyS6OxRuTSCcxy1ZZEwtkRxOJEsq6Yu0RDz3mM1bmStpLL/HaynaNbvu/PC1cjPySrPqcG9q4L1VbXTppxPA2nFTB48l8gqQGBrXyczxVak3QxVdEKdP1LpzA0+3RQqUvlH76jnrLEXEoakb8Ka0C6oj0dzLucP6i6w6AV9VZ1KhRCOEt3nwiH6ljbDYu2sJ8IC76L+QHneAUBYQiRwB/BTK0Axuf8mY9FfSkkmEFvvAfvNi4DiYJHOPmICc03X2F2LI1OYLnTi4b+76vnffuEc+5f7KX8vI7xVvdwEhJnkOnqrTWmSngkvMV2rEUNNov06+7j+8dA9cLfTrXyuXein1bYuNQiISRGdWzWdgKiOKILZb3zds9aHJi9hay+XGemD8c1e9KsjTp2Tb9YvTJqpUqSu7J2nyThulI24m7EXoaoOx3haJn9b/HSF6KWJEnUscv9tlMdLYbN+ESRclY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
